### ISSUE TITLE
PHP Fatal error:  Call to undefined method

### ISSUE THREAD

**Issue by ofedoryshyn** [piwik/plugin-QueuedTracking#11]
Hi,

I have always an error when processing data. Help me understand what am I doing wrong

```
/usr/local/php/bin/php /mnt/nginx/piwik/console queuedtracking:process
Starting to process request sets, this can take a while
PHP Fatal error:  Call to undefined method Piwik\Plugins\QueuedTracking\Queue\Manager::shouldRecordStatistics() in /mnt/nginx/piwik/plugins/QueuedTracking/Queue/Processor.php on line 68
```

**Comment by mattab** [comment]
Hi @ofedoryshyn 

please try upgrade your Piwik to the latest beta version: http://piwik.org/faq/how-to-update/faq_159/
Then upgrade the QueuedTracking to latest version. This should work, let us know here if you still have a problem!
