### ISSUE TITLE
Form Analytics has fallen off since we have enabled queued tracking

### ISSUE THREAD

**Issue by jjcitron** [piwik/plugin-QueuedTracking#126]
we enabled queued trackng on the 13th. since then we have seen a massive dropoff in form data coming into matomo across all of our properties. most have dropped to zero with the occasional spike which will show a submit here or there.

we do however have a property that is showing forms, although the resubmitter metric did see a fall off. 

the only platform change was to enable Queued tracking to redis.
Our platform is running in a load balanced, multi server enviroment.

![image](https://user-images.githubusercontent.com/8416525/75406555-bb810400-58de-11ea-9ba9-b6eb5fae715a.png)

**Comment by tsteur** [comment]
@jjcitron maybe reach out to our support at shop at innocraft.com and ideally send them a URL where you have the tracking code embedded so we can ensure tracking requests are still sent. Just to make sure it's related to queued tracking and not the tracking code or something else.

Queued tracking should handle these requests without any issues. There are commands like `queuedtracking:print-queued-requests` to print all queued requests and it may be worth testing if a form analytics request is present there after triggering it in the UI but depending on the system that request could be already processed or it might not be in the next X requests.

To debug some thoughts...
Set the number of requests to process at once to some very high number, like 500000. Then go to your UI and trigger these form requests, then execute the command `./console queuedtracking:print-queued-requests` in the Matomo directory. You should be able to see a request like `&fa_id=...`. If the tracking request is visible in the browser, but not in queued tracking, then something with the server setup in between may be wrong. 

Then set the number back to what it was previously. I haven't tested this procedure though.

**Comment by jjcitron** [comment]
we took a look at the console, and we do see the form activity hitting the server, there is something happening between that process and the data being available in matomo.

as forms are stored in their own table, is there a difference in the process from passing from the queue  to the visit log vs to the the log_form  that may be causing this that we can look into?

**Comment by tsteur** [comment]
@jjcitron there is no difference for Matomo no matter what table it is. We've been using it ourselves as well and it works nicely. What may happen with Form Requests is that they may be sent as a so called bulk request if there are multiple tracking requests in one particular browser session at once. Queued tracking should replay these without any issues though (we've never had any issues with it). It might not help but maybe you can send us the output of that command? not the full output maybe but the one related to form analytics? Just as a thought. It's unfortunately bit hard for us to tell what the problem could be without access to the system etc.

**Comment by jjcitron** [comment]
after digging into it, we discovered that our tracking js file may have been out of date as we moved it to another server to reduce load.

js files was updated with core updates, but not for plugins, which may have cuased the issue.

**Comment by tsteur** [comment]
thanks for letting us know @jjcitron
