### ISSUE TITLE
Redis Sentinel with DB ID != 0

### ISSUE THREAD

**Issue by RealKelsar** [piwik/plugin-QueuedTracking#128]
Hi,

Plugin Version: 3.3.6

I tried to use a different DB ID, which I need too, but that fails with sentinels enabled.

A clue gave me this:
https://github.com/matomo-org/plugin-QueuedTracking/issues/23

It is not possible to select a DB inside the Sentinel connection. Quicktest with DB 0 it works flawless. So somewhere a DB select must be removed I guess.

Thank you.

**Comment by tsteur** [comment]
@RealKelsar I'm not so much familiar with it but basically trying to guess maybe if https://github.com/matomo-org/plugin-QueuedTracking/pull/130 would work? Not sure where the DB should be configured and where not. 

Did you want to configure a DB for a specific redis within the sentinel or the sentinel itself?

**Comment by RealKelsar** [comment]
Hi,

appreciate the Feedback, will try tomorrow.

Basically a sentinel is a dumbed down Redis, it only ever has DB 0, as I understand it. So there never needs a DB to be configured.

**Comment by RealKelsar** [comment]
Hey,
from reading the Patch, that would make it kind of worse, since it would set the real client connection hard to DB 0, if I understood it correct.

The current master or credis does handle that internally a bit better, but that said the code currently inplace should work...

**Comment by RealKelsar** [comment]
Hi,
I am sorry, the problem was in front of my keyboard. On that cluster I never configured a higher DB Limit as 16 (default) so of course a higher ID would not work...
