### ISSUE TITLE
Call to undefined method shouldRecordStatistics()

### ISSUE THREAD

**Issue by andypl78** [piwik/plugin-QueuedTracking#13]
After updating to version 0.1.6 plugin error occurred

./console queuedtracking:process

PHP Fatal error:  Call to undefined method Piwik\Plugins\QueuedTracking\Queue\Manager::shouldRecordStatistics() in /var/www/domain.tld/web/plugins/QueuedTracking/Queue/Processor.php on line 68

Piwik version 2.13.1
PHP 5.6.9

**Comment by tsteur** [comment]
This should be fixed in version 0.1.7 which should be available soon. Please let us know in case you still have problems afterwards.
