### ISSUE TITLE
Redis password length

### ISSUE THREAD

**Issue by ghost** [piwik/plugin-QueuedTracking#131]
### The Problem

There is a 100 character limit on the length of the Redis password in `SystemSettings.php` starting on line 231.

Redis allows for much longer passwords. I use a Redis password that is longer than 100 characters. This may be totally insane/paranoid but it works for me and, why not?

### Steps to reproduce

1. Try to set a password in QueuedTracking longer than 100 characters.
2. Read the error message.

### Proposed solution

Increase this limit to 128 characters as a nice, round, familiar binary factor and allow for extreme paranoia. After all, your user base are probably leaning more toward the more security conscious anyway.

**Comment by tsteur** [comment]
Cheers @gillytech 
Created https://github.com/matomo-org/plugin-QueuedTracking/pull/132

**Comment by ghost** [comment]
Awesome, I somehow missed this one but glad it got some attention and is coming out in the v4 release!
