### ISSUE TITLE
Fehler bei processing

### ISSUE THREAD

**Issue by Malli88** [piwik/plugin-QueuedTracking#14]
Hallo zusammen,

habe Piwik 2.13.1 im einsatz und bekomme einen fehler beim processing des queued tracking plugins.

[root@ip-172-30-4-20 piwik]# ./console queuedtracking:process -vvv
PHP Fatal error:  Call to undefined method Piwik\Tracker::setTrackerDebugMode() in /usr/share/nginx/html/piwik/plugins/QueuedTracking/Commands/Process.php on line 46

weder mit einem cronjob noch mit der buildin lösung funktioniert es.

Eine schnelle hilfe wäre sehr schön. Danke im vorraus.

Grüße
Stephan Mallmann

**Comment by mattab** [comment]
Hi @Malli88 

can you try upgrade to Piwik 2.14.0 and report if the issue is maybe fixed?

**Comment by tsteur** [comment]
This should be fixed in version 0.1.7 which will be available soon. Please comment or reopen in case it still won't work for you
