### ISSUE TITLE
Missing in FAQ : how to quit the monitor ?

### ISSUE THREAD

**Issue by mathieuroquefort** [piwik/plugin-QueuedTracking#144]
Hello,
The FAQ indicates that we can look at how many requests are in the queue, with `./console queuedtracking:monitor`
But this command does not exit. Once there, we are stuck and can't get out.

I've tried `exit`, `q` and `esc` to exit, but none works :
```
$ ./console queuedtracking:monitor
Queue is enabled
Request sets in the queue will be processed automatically after a tracking request
Up to 1 workers will be used
Processor will start once there are at least 1 request sets in the queue
0 (0) request sets left in queue. disabled used memory (disabled peak). 0 workers active.        exit
0 (0) request sets left in queue. disabled used memory (disabled peak). 0 workers active.        
0 (0) request sets left in queue. disabled used memory (disabled peak). 0 workers active.        q
0 (0) request sets left in queue. disabled used memory (disabled peak). 0 workers active.        q
0 (0) request sets left in queue. disabled used memory (disabled peak). 0 workers active.        
0 (0) request sets left in queue. disabled used memory (disabled peak). 0 workers active.        

0 (0) request sets left in queue. disabled used memory (disabled peak). 0 workers active.        ^[
0 (0) request sets left in queue. disabled used memory (disabled peak). 0 workers active.        
```
Some more information in the FAQ would be welcome.

PS : thanks for the plugin. It is quite useful when there is a server migration to perform or a database to upgrade and we want to be sure not to loose any data.

**Comment by Findus23** [comment]
Hi,

Just like any other command line program you can quit it by pressing CTRL+C.
Things like exit and q are not working because it is not an interactive program.

**Comment by mathieuroquefort** [comment]
Thank you.
But what about adding it to the FAQ ?
Not everyone uses command line every day and knows this kind of thing.

**Comment by tsteur** [comment]
Thanks @mathieuroquefort Added this to https://github.com/matomo-org/plugin-QueuedTracking/blob/4.x-dev/docs/faq.md
