### ISSUE TITLE
queuedtracking:process creates heavy load on SQL Database (after Matomo 4.x.x Update)

### ISSUE THREAD

**Issue by csautter** [piwik/plugin-QueuedTracking#151]
We have a large Matomo Setup (>1Mio Requests/Day) with QueuedTracking enabled. After Updating from Matomo 3 to 4 we had Trouble with high CPU Load (100%) on our SQL Server. As result the QueuedTracking plugin was working very slowly and the queue permanently increases.

After some investigation i figured out that the queuedtracking:process command triggers many SQL SELECT queries like:

````SQL
SELECT visit_last_action_time, visit_first_action_time, idvisitor, idvisit, user_id, visit_exit_idaction_url, visit_exit_idaction_name, visitor_returning, visitor_seconds_since_first, visitor_seconds_since_order, visitor_count_visits, visit_goal_buyer, location_country, location_region, location_city, location_latitude, location_longitude, referer_name, referer_keyword, referer_type, idsite, profilable, visit_entry_idaction_url, visit_total_actions, visit_total_interactions, visit_total_searches, referer_url, config_browser_name, config_client_type, config_device_brand, config_device_model, config_device_type, visit_total_events, visit_total_time, location_ip, location_browser_lang, campaign_content, campaign_group, campaign_id, campaign_keyword, campaign_medium, campaign_name, campaign_placement, campaign_source, last_idlink_va, custom_dimension_1, custom_dimension_2, custom_dimension_3, custom_dimension_4, custom_dimension_5, custom_dimension_6  FROM log_visit WHERE visit_last_action_time >= '2021-06-15 06:38:17' AND visit_last_action_time <= '2021-06-15 07:38:17' AND idsite = '1' AND config_id = 'xxx'
ORDER BY visit_last_action_time DESC
LIMIT 1
````
**The avg. runtime of this query was 19 seconds.**

Creating an Index over (idsite, config_id) reduces the query runtime **down to 500ms**. This is fast enough for now. I'm not sure if it's the optimum.
````SQL
create index log_visit_idsite_config_id_index
	on log_visit (idsite, config_id);
````

Here is the DLL for the table as it is.
````SQL
create table if not exists log_visit
(
	idvisit bigint(10) unsigned auto_increment
		primary key,
	idsite int unsigned not null,
	idvisitor binary(8) not null,
	visit_last_action_time datetime not null,
	config_id binary(8) not null,
	location_ip varbinary(16) not null,
	user_id varchar(200) null,
	visit_first_action_time datetime not null,
	visit_goal_buyer tinyint(1) null,
	visit_goal_converted tinyint(1) null,
	visitor_days_since_first smallint unsigned null,
	visitor_days_since_order smallint unsigned null,
	visitor_returning tinyint(1) null,
	visitor_count_visits int(11) unsigned default 0 not null,
	visit_entry_idaction_name int unsigned null,
	visit_entry_idaction_url int(11) unsigned null,
	visit_exit_idaction_name int unsigned null,
	visit_exit_idaction_url int unsigned default 0 null,
	visit_total_actions int(11) unsigned null,
	visit_total_interactions mediumint unsigned default 0 null,
	visit_total_searches smallint unsigned null,
	referer_keyword varchar(255) null,
	referer_name varchar(255) null,
	referer_type tinyint(1) unsigned null,
	referer_url varchar(1500) null,
	location_browser_lang varchar(20) null,
	config_browser_engine varchar(10) null,
	config_browser_name varchar(40) null,
	config_browser_version varchar(20) null,
	config_device_brand varchar(100) null,
	config_device_model varchar(100) null,
	config_device_type tinyint(100) null,
	config_os char(3) null,
	config_os_version varchar(100) null,
	visit_total_events int(11) unsigned null,
	visitor_localtime time null,
	visitor_days_since_last smallint unsigned null,
	config_resolution varchar(18) null,
	config_cookie tinyint(1) null,
	config_director tinyint(1) null,
	config_flash tinyint(1) null,
	config_gears tinyint(1) null,
	config_java tinyint(1) null,
	config_pdf tinyint(1) null,
	config_quicktime tinyint(1) null,
	config_realplayer tinyint(1) null,
	config_silverlight tinyint(1) null,
	config_windowsmedia tinyint(1) null,
	visit_total_time int(11) unsigned not null,
	location_city varchar(255) null,
	location_country char(3) null,
	location_latitude decimal(9,6) null,
	location_longitude decimal(9,6) null,
	location_region char(3) null,
	custom_var_k1 varchar(200) null,
	custom_var_v1 varchar(200) null,
	custom_var_k2 varchar(200) null,
	custom_var_v2 varchar(200) null,
	custom_var_k3 varchar(200) null,
	custom_var_v3 varchar(200) null,
	custom_var_k4 varchar(200) null,
	custom_var_v4 varchar(200) null,
	custom_var_k5 varchar(200) null,
	custom_var_v5 varchar(200) null,
	last_idlink_va bigint unsigned null,
	custom_dimension_1 varchar(255) null,
	custom_dimension_2 varchar(255) null,
	custom_dimension_3 varchar(255) null,
	custom_dimension_4 varchar(255) null,
	custom_dimension_5 varchar(255) null,
	campaign_content varchar(255) null,
	campaign_id varchar(100) null,
	campaign_keyword varchar(255) null,
	campaign_medium varchar(255) null,
	campaign_name varchar(255) null,
	campaign_source varchar(255) null,
	custom_dimension_6 varchar(255) null,
	location_provider varchar(200) null,
	visitor_seconds_since_first int(11) unsigned null,
	visitor_seconds_since_order int(11) unsigned null,
	visitor_seconds_since_last int(11) unsigned null,
	profilable tinyint(1) null,
	config_client_type tinyint(1) null,
	campaign_group varchar(255) null,
	campaign_placement varchar(100) null
);

create index log_visit_idsite_config_id_index
	on log_visit (idsite, config_id);
````

**Comment by diosmosis** [comment]
@csautter sorry for the trouble and thanks for creating a report! This seems to be a similar issue to https://github.com/matomo-org/matomo/issues/16904. Some questions:

* would you be able to test if the query is faster with `idvisit DESC` instead of `visit_last_action_time DESC`?
* would you be able to provide the EXPLAINs for the queries?
* can you check that there is an index on the log_visit table already like `INDEX index_idsite_config_datetime (idsite, config_id, visit_last_action_time),`? (this is added by matomo)
* and for the queries that are slow, can you check how many visits are being looked at? For example, `SELECT COUNT(*)  FROM log_visit WHERE visit_last_action_time >= '2021-06-15 06:38:17' AND visit_last_action_time <= '2021-06-15 07:38:17' AND idsite = '1' AND config_id = 'xxx'`.

**Comment by csautter** [comment]
> would you be able to test if the query is faster with idvisit DESC instead of visit_last_action_time DESC

This makes no measurable difference.

> would you be able to provide the EXPLAINs for the queries?

| id | select\_type | table | partitions | type | possible\_keys | key | key\_len | ref | rows | filtered | Extra |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | SIMPLE | log\_visit | NULL | ref | log\_visit\_idsite\_config\_id\_index | log\_visit\_idsite\_config\_id\_index | 12 | const,const | 1 | 11.11 | Using index condition; Using where; Using filesort |

> can you check that there is an index on the log_visit table already like INDEX index_idsite_config_datetime (idsite, config_id, visit_last_action_time),? (this is added by matomo)

That's the point. All indicies were missing.
There must happended a mistake at some Point while updating. We had big struggles with updating the log_visit table. With a table size over 500 GB the updater and also manual queries failed multiple times. Optimizing the SQL server settings didn't solved the problem.
As solution i decided to copy the table structure and the data partial. Would say that indicies got lost here.

Maybe it's possible to build a final update check to identify such mistakes? Extending the Matomo "System Check" would also be helpful.

> and for the queries that are slow, can you check how many visits are being looked at? For example, SELECT COUNT(*) FROM log_visit WHERE visit_last_action_time >= '2021-06-15 06:38:17' AND visit_last_action_time <= '2021-06-15 07:38:17' AND idsite = '1' AND config_id = 'xxx'

result 0 for this query

**Finally after recreating all default indicies the query runtime is still at 500 ms.**
Maybe it's possible to reduce the database lookups with an optional redis cache. Could also help with the related issue https://github.com/matomo-org/matomo/issues/16904

Thank you for your help @diosmosis !
