### ISSUE TITLE
Randomized Queue Distribution instead of MD5 of IP/ID

### ISSUE THREAD

**Issue by sw-waterford** [piwik/plugin-QueuedTracking#160]
Is there a reason distribution is based on the IP or Visitor ID I am finding the distribution is heavily weighted on queue 1 and 2 out of 8 which makes it very difficult to process high volumes of traffic effectively. Wouldn't you get a more even distribution using a randomized or round robin pattern of distribution would this be worth a pull request?

**Comment by tsteur** [comment]
@sw-waterford it's important visitors with the same IP/ visitorId are put in the same queue. Otherwise the tracking requests might not be replayed in the correct order which then causes the data to be wrong. For example reports like "Entry pages" and "Exit pages" etc. I hope this clarifies it.
