### ISSUE TITLE
Importing data with log importer queues all req in the same redis queue instead of distributing req across all queues

### ISSUE THREAD

**Issue by jaceklubzinski** [piwik/plugin-QueuedTracking#18]
Hello,

* run import command: `/srv/piwik/current/misc/log-analytics/import_logs.py /srv/logs/$log --url=http://front.piwiktest --config=/srv/piwik/current/config/config.ini.php --recorders=2 --recorder-max-payload-size=300 --log-format-regex='(?P<ip>\S+) \S+ \S+ \[(?P<date>.*?) (?P<timezone>.*?)\] "\S+ (?P<path>.*?) \S+" (?P<status>\S+) (?P<length>\S+) "(?P<referrer>.*?)" "(?P<user_agent>.*?)" (?P<host>[\w\-\.]*)(?::\d+)? \S+ \S+' --retry-max-attempts=100`

We import 150GB of logs

* run this command `/srv/piwik/current/console --piwik-domain=http://front.piwiktest queuedtracking:monitor`

We got this output. You can see that almost all of the req are in one queue

```
Up to 8 workers will be used

Processor will start once there are at least 25 request sets in the queue

205395 (22+4+14+205286+10+20+20+19) request sets left in queue. 8.01G used memory (9.82G peak). 1 workers active
```

* Expected to get more distributed count of req in each queue, so that processing of queue is much faster.

**Comment by tsteur** [comment]
Log importer should not be used in combination with QueuedTracking. And if you still have to I'd try to use `--recorder-max-payload-size=1` to not do any bulk tracking requests

**Comment by tsteur** [comment]
If this doesn't help I need an example of the log output to reproduce. We generate a hash of the visitorId and based on this move it in different queues. It would mean they have all pretty much same visitorId

**Comment by tsteur** [comment]
Actually QueuedTracking might be compatible with LogImporter by now but if they do not have a visitorId set, and all requests have same IP (which I guess could be the case here), then there's probably not much we can do. I'd need an example

**Comment by mattab** [comment]
Hi @jaceklubzinski do you still experience problems? please provide more information so we can understand the problem and help provide a fix

**Comment by jaceklubzinski** [comment]
Hi,
with settings like this, the queue does not grow to the size of several gigabytes
```
Up to 8 workers will be used
Processor will start once there are at least 5 request sets in the queue
10891 (1762+8+7+7+16+8+6+9077) request sets left in queue. 218.07M
```
but still req are not distributed equally. In a short time I provide more information.

**Comment by quba** [comment]
Even without log importer it happens that one queue is bigger than other.

In our case we have 16 queues and all are almost empty except of one which has currently 300k requests.

Possible reasons:
- more idvisitors starting with given char,
- worker slower for given idvisitors,
- issue in algorithm that is choosing the queue.

**Comment by tsteur** [comment]
How's the data tracked? Via piwik.js? If tracked different, and if there is no visitorId, it can be likely that most IP addresses start eg with `1` as in `1xx.` or so and then they go into the same queue (queue 2)

**Comment by tsteur** [comment]
I've been thinking a few times how to visualize it but not sure how. Eg I thought reading all visitorIds (or fallback IP) out of all queues, then list eg top 100 aggregated visitorIds or IP if no visitorId given per queue but not sure if it would help

**Comment by quba** [comment]
I just realized that in this case we have many different tracking methods.  It's possible that we have there also PHP or other backend tracking client where vidistor ID is not generated via javascript.

Additionally, yesterday it was one queue, today it looks a little bit different:
```
2489760 (108+171838+347755+176+557775+152299+87+149+153549+182912+140+2474+103030+292093+484909+40466) request sets left in queue. 12.91G used memory (12.91G peak). 14 workers active. 
```

I was also thinking about the disk space it requires. Maybe it would be possible to minimize it somehow by not storing some data like not important headers, etc.?

**Comment by quba** [comment]
Sample with 8 workers:
```
350085 (4633+162523+296+4356+169988+3893+942+3454)
```
This confirms your theory.

**Comment by tsteur** [comment]
How does it come that there are so many requests in the queue? Was there a peak or are they just not fast enough to process it and it gets bigger and bigger?

Re IPs it might be better to `md5($ip)` and then move it into a queue based on first character so IPs are more randomized. Problem is I'd kinda need to check how long an update script for this would take (redistributing the existing requests into correct queue)

**Comment by tsteur** [comment]
If many requests come from same IP it would still result in not evenly distributed queues but there's not much we can do in this case

**Comment by quba** [comment]
md5 should work better in that case, I wouldn't assume that requests are from the same IP, rather many IPs starting with 1xx.

Regarding this case, it was in peak hours, in this case around 660req/s. Tomorrow we are going to analyze if this was because of workers being to slow or because of DB load, I'd say that workers are to slow.

**Comment by quba** [comment]
I don't think that the update script is needed. it's possible to simply disable queue, process all requests and then reenable.

**Comment by tsteur** [comment]
Yeah I'm also thinking of other users that use this plugin. If you disable the plugin we possibly have the problem to insert tracking requests directly while it is disabled and older requests maybe afterwards or in parallel (unless you use log import but it's not trivial). I presume a "redistribution" process wouldn't take too long.

**Comment by tsteur** [comment]
My idea would be to create a new command that pretends to use the whole IP for deciding in which queue to move a visitor and at the end print an overview of how many requests went into which queue. This way we can verify it would actually help to change it and we get roughly an idea how long it would take to redistribute the requests although it would not be accurate. I'd also print how many requests there are with visitorId and how many without (IP address is used for deciding into which group a visitor is moved then).

**Comment by tsteur** [comment]
Actually, I just noticed it already uses the whole IP for hashing it see https://github.com/piwik/plugin-QueuedTracking/blob/0.2.4/Queue/Manager.php#L198-L200 . I'm creating a new console command anyway just to get a bit more insight into this data

**Comment by tsteur** [comment]
@quba I pushed a new command to analyze the data here: https://github.com/piwik/plugin-QueuedTracking/blob/analyze/Commands/Analyze.php

For now there's maybe not too much information but we can get more insights step by step maybe. It analyzed 5.000 requests in less than a second in my local virtual machine so it might be quite fast. Output is like this:

```bash
Currently analyzing queue 3 of 3 (500 of about 499 request sets). Stats: forcedUserId: 0, forcedVisitorId: 42, visitorId: 5001, invalidRequests: 0, useVisitorIdForSharding: 5043, useIPForSharding: 11, requestSetsWithMultipleRequests: 56, requestSetsWithOneRequest: 1713, OldDistribution: 1943 + 1605 + 1506, NewDistribution: 1943 + 1605 + 1506        

Starting letter analysis: 0: 419, 1: 262, 2: 219, 3: 332, 4: 153, 5: 267, 6: 252, 7: 490, 8: 279, 9: 252, a: 246, b: 184, c: 435, d: 454, e: 557, f: 253
Analysed 5054 requests within 1769 request sets in 1 second(s)
```

`OldDistribution` and `NewDistribution` should currently show same numbers but once we try different algorithms we can test old distribution vs new distribution and see if it changes something.

**Comment by tsteur** [comment]
@quba do you mind executing the command and posting the output?

**Comment by quba** [comment]
I'll ask sys-admins (cc @marucha) to post the output here.

**Comment by quba** [comment]
See attached file. Don't know why output is posted serveral times for each queue. 

```
7415404 (1014860+869747+457513+22+810576+654420+123899+811423+707707+101402+493440+789333+31637+12984+536420+21) request sets left in queue. 25.41G used memory (25.47G peak). 11 workers active.
```
[analyze2.txt.gz](https://github.com/piwik/plugin-QueuedTracking/files/88677/analyze2.txt.gz)

**Comment by quba** [comment]
Looks more like an issue with workers performance than queues distribution.

**Comment by tsteur** [comment]
Thx for that. Almost feels like we need to think about else in the future. Like allowing multiple workers to work on the same queue by looking into the requests before picking them out of the queue (adds a lot of overhead but would be still faster in such a scenario). 

Just to summarise the result so not every has to look into it:

> Analysed 7811492 requests within 7811520 request sets in 5643 second(s)

> Starting letter analysis: 0: 1053472, 1: 883528, 2: 429301, 3: 20, 4: 858150, 5: 636340, 6: 60383, 7: 866202, 8: 763731, 9: 138248, a: 544763, b: 851035, c: 14195, d: 51770, e: 595274, f: 65080

> Stats: forcedUserId: 3331, forcedVisitorId: 0, visitorId: 7777044, invalidRequests: 0, useVisitorIdForSharding: 7780369, useIPForSharding: 31123, requestSetsWithMultipleRequests: 0, requestSetsWithOneRequest: 7811520

So it uses mainly the visitor ID for sharding and it seems to spread them evenly across queues. The workers should pick a queue to work on randomly after eg every 25 requests to make sure all queues are being worked on so not really sure whether it's related to worker performance or some other logic fail. Looking at the code I noticed I was using `rand` and will replace it with `mt_rand` here: https://github.com/piwik/plugin-QueuedTracking/blob/0.2.4/Queue/Manager.php#L234-L235 Maybe `rand` produces often similar numbers which is possible. This means it would always remove some requests from some queues first before working on others. I issued: https://github.com/piwik/plugin-QueuedTracking/pull/30

**Comment by tsteur** [comment]
I released a new version 0.2.5 which uses `mt_rand` when available. Do you mind giving it a try?

**Comment by tsteur** [comment]
Is the latest version already used? Do we maybe know if it got better since we use `mt_rand`?

**Comment by quba** [comment]
Yep, afaik it's better. You can confirm this tomorrow with sysadmins.

**Comment by mattab** [comment]
@jaceklubzinski @quba  could this issue be closed maybe?

**Comment by quba** [comment]
Yes
