### ISSUE TITLE
With multiple workers most of the requests are put into trackingQueueV1

### ISSUE THREAD

**Issue by kevinkopf** [piwik/plugin-QueuedTracking#188]
Steps to reproduce:
1. Use JavaScript tracker
2. Do not use the log importer
3. Provider plugin not installed
4. Install the plugin
5. Set up tracking with Redis 
6. Set up 16 workers through GUI
7. Go play some minecraft until you almost lose your job. Just to pass time, you know :sweat_smile: 
8. Run `./console queuedtracking:monitor`

Result:
`trackingQueueV1` has substantionally more requests, than other queues. The option "Process during tracking request" seemingly does not affect the queue number. At least I haven't noticed any correlation. 
![image](https://user-images.githubusercontent.com/45859859/187005446-2acf44cc-c1bc-4a7a-afa9-99ccb8de3f19.png)

Similar problem was reported [here](https://forum.matomo.org/t/issues-with-queuedtracking-plugin/42203) as well:

> 2808222 (0+2807543+0+0+0+0+675+4) request sets left in queue. 3.62G used memory (3.62G peak). 1 workers active.

and maybe a couple of other places I cant recall now. I managed to track the uneven distribution of requests to [this function](https://github.com/matomo-org/plugin-QueuedTracking/blob/4.x-dev/Queue/Manager.php#L214).

Now I know, that @tsteur said [here](https://github.com/matomo-org/plugin-QueuedTracking/issues/153#issuecomment-893007510)

> Generally, Matomo will put all requests for the same User, Visitor and IP address into the same queue.

My question is: Is there a specific reason to do it like so? I mean, putting all requests for the same User, Visitor and IP address into the same queue. Wouldn't it be better to try to evenly distribute the requests among queues? Are there specific relations, that might break if we don't put it into the same queue?

If not, I'd go with a simple `rand`, which statistically would ensure uniform distribution of requests:

```
    protected function getQueueIdForVisitor($visitorId)
    {
        return rand(0, $this->numQueuesAvailable - 1);
    }
```
simply keeping `$visitorId` for backwards compatibility for now.

**Comment by snake14** [comment]
Hi @kevinkopf . Thank you for taking the time to create this issue. I have confirmed that is the expected behaviour. Matomo tries to split the requests as evenly as possible between queues, but it also tries to keep requests from the same visitor/user in the same queue. We do this to ensure that we can replay events in the correct order.

I'm marking this issue as closed, but please feel free to let me know if you think there's cause to have it re-opened or if you have any further questions.

**Comment by heurteph-ei** [comment]
Hi @snake14, @kevinkopf 
Maybe the problem comes from another reason. See for example:
https://forum.matomo.org/t/urgent-queued-tracking-assistance-needed/41014/3
I think this should be added somewhere in the QueuedTracking FAQ (and plug-in FAQ in marketplace)
