### ISSUE TITLE
Is there any option to force the process even if it does not meet the # of requests that are processed in one batch?

### ISSUE THREAD

**Issue by jrca025** [piwik/plugin-QueuedTracking#189]
Is there a way to force process the queued requests even if it does not reach this value?
![image](https://user-images.githubusercontent.com/89201548/191671975-22bf0533-1c1c-4487-9292-af1377bee1a2.png)

**Comment by AltamashShaikh** [comment]
@jrca025 Can you try this command `./console queuedtracking:process`  ?

**Comment by jrca025** [comment]
@AltamashShaikh 
It is not processing until it reaches at least 25.
![image](https://user-images.githubusercontent.com/89201548/191684450-2cab39e9-311e-4641-9281-25d55c62200c.png)

**Comment by AltamashShaikh** [comment]
@jrca025 Try this ` ./console queuedtracking:process  --force-num-requests-process-at-once={YOUR_DESIRED_VALUE}`

**Comment by jrca025** [comment]
> 

@AltamashShaikh is the desired_value works like the # of batch requests? Wherein if I set that desired value to 10, but my current queue is just around 5. It will not process it?

**Comment by AltamashShaikh** [comment]
@jrca025 It won't process all at once if you want to process all try `./console queuedtracking:process  --force-num-requests-process-at-once=1`

**Comment by AltamashShaikh** [comment]
@jrca025 The above is not recommended since it defeats the purpose of plugin

**Comment by jrca025** [comment]
> @jrca025 The above is not recommended since it defeats the purpose of plugin

Yes. I just want it to process the remaining requests in queue even if it does not reach the # of batch requests.

**Comment by AltamashShaikh** [comment]
@jrca025 The above should do the needful
