### ISSUE TITLE
Traces of errors in Queue tracking

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/plugin-QueuedTracking#193]
Hi Matomo!

As seen there: #192 when there is tracking errors, they are not visible anymore when the Queue tracking is enabled.

Another example is available for such tracking failures (logged in my error log file, when Queue tracking is disabled):
```
httpd: -|matomo-server|t="Wed Sep 28 16:00:29 2022" rip="10.221.0.0" ip="-" uid="YzRTfXgzNdXEzkW1l3-WAQAAAH4" severity="php7:notice" v="matomo-server" msg="Error in Matomo (tracker): Invalid idSite: '0'"
httpd: -|matomo-server|t="Wed Sep 28 16:32:02 2022" rip="10.221.0.0" ip="-" uid="YzRa4oLUbIkTEhcvEw4YAgAAABE" severity="php7:notice" v="matomo-server" msg="Error in Matomo (tracker): Invalid idSite: '0'"
httpd: -|matomo-server|t="Wed Sep 28 16:52:17 2022" rip="10.221.0.0" ip="-" uid="YzRfoIWi0NQ47ify7gCZ@gAAAFs" severity="php7:notice" v="matomo-server" msg="Error in Matomo (tracker): An unexpected website was found in the request: website id was set to '22' ."
httpd: -|matomo-server|t="Wed Sep 28 16:52:31 2022" rip="10.221.0.0" ip="-" uid="YzRfryi-osCyKrkgT5oSygAAAHc" severity="php7:notice" v="matomo-server" msg="Error in Matomo (tracker): An unexpected website was found in the request: website id was set to '22' ."
httpd: -|matomo-server|t="Wed Sep 28 16:52:51 2022" rip="10.221.0.0" ip="-" uid="YzRfw-sayOoO8-snhrbFwgAAABI" severity="php7:notice" v="matomo-server" msg="Error in Matomo (tracker): An unexpected website was found in the request: website id was set to '22' ."
httpd: -|matomo-server|t="Wed Sep 28 17:53:29 2022" rip="10.221.0.0" ip="-" uid="YzRt@RABku7qpRTAXNminQAAAFM" severity="php7:notice" v="matomo-server" msg="Error in Matomo (tracker): An unexpected website was found in the request: website id was set to '22' ."
```
When the Queue tracking is enabled, above errors are not logged anywhere anymore...

**Comment by snake14** [comment]
Hi @heurteph-ei. Thank you for the excellent suggestion. It's definitely odd that errors aren't getting logged like they usually do when queued tracking is enabled. I will mark this issue to be prioritised by our product team.

**Comment by heurteph-ei** [comment]
(and also the tracking error being visible in the **Tracking failures** admin report):
![image](https://user-images.githubusercontent.com/79993552/196444557-302d6459-342a-48c4-9d42-1b6b9fcc6d50.png)

**Comment by AltamashShaikh** [comment]
@heurteph-ei With release of version [4.07](https://github.com/matomo-org/plugin-QueuedTracking/releases/tag/4.0.7) this issue should be fixed, please let us know if this is still an issue and we can reopen the issue
