### ISSUE TITLE
DNT support

### ISSUE THREAD

**Issue by quba** [piwik/plugin-QueuedTracking#2]
Hi,

haven't had a chance to go through the code, but I have a question. Does this solution support DNT header?

We could either check current Piwik privacy settings and reject requests with this header set or add additional parameter to the tracking requests, which adds information about this header. Maybe it's already implemented - if yes, then please close this issue.

Cheers!

**Comment by quba** [comment]
@tsteur ping

**Comment by tsteur** [comment]
I haven't tested it specifically but it should work as we do restore the user's PHP `$_SERVER` environment when actually executing the tracking request and it is detected via this:

```
    protected function isHeaderDntFound()
    {
        return (isset($_SERVER['HTTP_X_DO_NOT_TRACK']) && $_SERVER['HTTP_X_DO_NOT_TRACK'] === '1')
            || (isset($_SERVER['HTTP_DNT']) && substr($_SERVER['HTTP_DNT'], 0, 1) === '1');
    }
```
