### ISSUE TITLE
Error on queuedtracking:process

### ISSUE THREAD

**Issue by mathiaspalmqvist** [piwik/plugin-QueuedTracking#206]
Hi,

I saw that all my websites in Matomo had started showing 0 in visitors per day after working perfectly for over a year. Double checked with the database and log_visit had no new rows since Monday. Went through my cronjobs and saw that `./console queuedtracking:process` returns an error message.

The error:
```
Starting to process request sets, this can take a while
Uncaught exception in /home/user/matomo.domain/vendor/matomo/device-detector/ClientHints.php line 193:
array_combine(): Argument #1 ($keys) and argument #2 ($values) must have the same number of elements
```

./console queuedtracking:test
```
Settings that will be used:
Backend: redis
NumQueueWorkers: 1
NumRequestsToProcess: 50
ProcessDuringTrackingRequest: 0
QueueEnabled: 0

Redis backend only settings (does not apply when using MySQL backend):
Host: 127.0.0.1
Port: 6379
Timeout: 0
Password: 
Database: 0
UseSentinelBackend: 0
SentinelMasterName: mymaster

Version / stats:
PHP version: 8.1.2
Uname: Linux Matomo.domain 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64
PHPRedis version: 5.3.7
Backend version: 5.0.7
Memory: array (
  'used_memory' => 12032904,
  'used_memory_human' => '11.48M',
  'used_memory_rss' => 14385152,
  'used_memory_rss_human' => '13.72M',
  'used_memory_peak' => 12033024,
  'used_memory_peak_human' => '11.48M',
  'used_memory_peak_perc' => '100.00%',
  'used_memory_overhead' => 846478,
  'used_memory_startup' => 796224,
  'used_memory_dataset' => 11186426,
  'used_memory_dataset_perc' => '99.55%',
  'allocator_allocated' => 12227776,
  'allocator_active' => 12558336,
  'allocator_resident' => 15515648,
  'total_system_memory' => 2004496384,
  'total_system_memory_human' => '1.87G',
  'used_memory_lua' => 39936,
  'used_memory_lua_human' => '39.00K',
  'used_memory_scripts' => 416,
  'used_memory_scripts_human' => '416B',
  'number_of_cached_scripts' => 2,
  'maxmemory' => 0,
  'maxmemory_human' => '0B',
  'maxmemory_policy' => 'noeviction',
  'allocator_frag_ratio' => 1.03,
  'allocator_frag_bytes' => 330560,
  'allocator_rss_ratio' => 1.24,
  'allocator_rss_bytes' => 2957312,
  'rss_overhead_ratio' => 0.93,
  'rss_overhead_bytes' => -1130496,
  'mem_fragmentation_ratio' => 1.2,
  'mem_fragmentation_bytes' => 2414168,
  'mem_not_counted_for_evict' => 0,
  'mem_replication_backlog' => 0,
  'mem_clients_slaves' => 0,
  'mem_clients_normal' => 49694,
  'mem_aof_buffer' => 0,
  'mem_allocator' => 'jemalloc-5.2.1',
  'active_defrag_running' => 0,
  'lazyfree_pending_objects' => 0,
)
MaxMemory Eviction Policy config: noeviction
MaxMemory config: 0

Performing some tests:
Redis is connected: 1
Connection works in general
Success for method set(testKey, value)
Success for method setnx(testnxkey, value)
Success for method setex(testexkey, 5, value)
Success for method set(testKeyWithNx, value, array (0 => 'nx',))
Success for method set(testKeyWithEx, value, array ('ex' => 5,))
Initial expire seems to be set correctly
setIfNotExists works fine
expireIfKeyHasValue seems to work fine
Extending expire seems to be set correctly
expireIfKeyHasValue correctly expires only when the value is correct
Expire is still set which is correct
deleteIfKeyHasValue seems to work fine
List feature seems to work fine

Done
```

**Comment by snake14** [comment]
Hi @mathiaspalmqvist . Thank you for taking the time to create this issue. It sounds like you didn't recently upgrade Matomo or the QueuedTracking plugin, correct? What versions are you currently running? I didn't see that the information above. Would you be able to try upgrading Matomo and the plugin?

**Comment by mathiaspalmqvist** [comment]
Hi @snake14,

I have the latest version of Matomo.

I'm running:
- PHP 8.1.2
- Matomo 4.13.3
- QueuedTracking 4.0.6

**Comment by snake14** [comment]
Thank you @mathiaspalmqvist . Do you recall when you made each of those 3 upgrades?

**Comment by mathiaspalmqvist** [comment]
I'm sorry, @snake14, but I do not know. As we are several people that have access to the system. But I know that no one has installed any plugins or made any other changes. We use the "You have an update" button on the dashboard.

But I can see that all the core files were changed on 31 January.

**Comment by snake14** [comment]
Thanks @mathiaspalmqvist . Sounds like it wasn't directly caused by the upgrade if there was about a week between the upgrade and the issue starting.

This seems related to a [comment from another customer](https://github.com/matomo-org/matomo/issues/19806#issuecomment-1428420679) on a core issue. It looks like one of our core developers [created a patch](https://github.com/matomo-org/device-detector/pull/7350/files), but I'm not sure how long it's going to be until Matomo 4.13.4 is released. Could you maybe try manually applying that patch to ClientHints.php and see if that resolves your issue?

**Comment by mathiaspalmqvist** [comment]
The patch works, thanks you so much @snake14 !

**Comment by snake14** [comment]
@mathiaspalmqvist Excellent! I'm very happy to hear that. I hope you have a wonderful day :+1:

**Comment by chcioni** [comment]
I have the same problem.
I'm running:

    PHP 7.4.30
    Matomo 4.14.2
    QueuedTracking 4.0.6

Which at some point started logging errors:
PHP Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, null given in /var/www/html/vendor/matomo/device-detector/ClientHints.php:264\nStack trace:\n#0 /var/www/html/vendor/matomo/device-detector/ClientHints.php(264): trim()\n#1

but the ./console queuedtracking:test not report issue.

**Comment by snake14** [comment]
Hi @chcioni . I'm sorry to hear that you're experiencing this problem. If you can pop the oldest record from your queue, processing should resume. We have [a similar issue](https://github.com/matomo-org/plugin-QueuedTracking/issues/194) that is still open and we're hoping to release an improvement to the plugin in the next few weeks.
