### ISSUE TITLE
One queue completely stuck, not processing.

### ISSUE THREAD

**Issue by skitoxe** [piwik/plugin-QueuedTracking#211]
Hello team! 

Our matomo instance stopped reciving tracking requests yesterday. 
And after troubleshooting i found that all requests were stuck in the queue and has built up to over 800.000 requests.  And were'nt being processed.
We started to further troubleshoot and checked redis, mariadb and everything else. Restarted everything just to make sure.

If i try to manually run the queue it only shows below, and nothing happens.
```
$ ./console queuedtracking:process --queue-id=0 -vvv
Forcing queue ID: 0
Starting to process request sets, this can take a while

This worker finished queue processing with 0req/s (0 requests in 0.01 seconds)

```
We usually have 1 queue with 1 worker. Configured to process during tracking requests after 25 requests in queue.
And after all the troubleshooting i changed that to 16 workers on 16 queues.
After that all requests that end up in queues 1-15 goes right through and gets processed correctly.
So now most requests are going through.
But queue 0 is still stuck.
**And eventually it will fill up memory and crash.**

It's like its a dangling request that cant be processed at the front of the queue that holds up the rest of the queue.

But i cant for the life of me find a way to "pop/remove" the first request. And i cant find a way to clear the queue either. 
We have som fairly high trafficked sites on our instance so ideally i dont want to loose the data is queue 0. I want to remove just the first couple of ones to get it to process the rest.

Please help, i will send this in to matomo support via e-mail as well and link to this issue.

Output from queuedtracking:test:
```Settings that will be used:
Backend: redis
NumQueueWorkers: 16
NumRequestsToProcess: 25
ProcessDuringTrackingRequest: 1
QueueEnabled: 1

Redis backend only settings (does not apply when using MySQL backend):
Host: <REDACTIED HOSTNAME>
Port: 6379
Timeout: 0
Password:
Database: 12
UseSentinelBackend: 0
SentinelMasterName: mymaster

Version / stats:
PHP version: 8.0.24
Uname: Linux <REDACTIED HOSTNAME> 4.18.0-425.13.1.el8_7.x86_64 #1 SMP Thu Feb 2 13:01:45 EST 2023 x86_64
PHPRedis version: 5.3.7
Backend version: 6.2.7
Memory: array (
  'used_memory' => 1221872416,
  'used_memory_human' => '1.14G',
  'used_memory_rss' => 1254158336,
  'used_memory_rss_human' => '1.17G',
  'used_memory_peak' => 1222772912,
  'used_memory_peak_human' => '1.14G',
  'used_memory_peak_perc' => '99.93%',
  'used_memory_overhead' => 838264,
  'used_memory_startup' => 812024,
  'used_memory_dataset' => 1221034152,
  'used_memory_dataset_perc' => '100.00%',
  'allocator_allocated' => 1222022368,
  'allocator_active' => 1225138176,
  'allocator_resident' => 1247199232,
  'total_system_memory' => 25023225856,
  'total_system_memory_human' => '23.30G',
  'used_memory_lua' => 37888,
  'used_memory_lua_human' => '37.00K',
  'used_memory_scripts' => 416,
  'used_memory_scripts_human' => '416B',
  'number_of_cached_scripts' => 2,
  'maxmemory' => 4294967296,
  'maxmemory_human' => '4.00G',
  'maxmemory_policy' => 'noeviction',
  'allocator_frag_ratio' => 1.0,
  'allocator_frag_bytes' => 3115808,
  'allocator_rss_ratio' => 1.02,
  'allocator_rss_bytes' => 22061056,
  'rss_overhead_ratio' => 1.01,
  'rss_overhead_bytes' => 6959104,
  'mem_fragmentation_ratio' => 1.03,
  'mem_fragmentation_bytes' => 32453880,
  'mem_not_counted_for_evict' => 0,
  'mem_replication_backlog' => 0,
  'mem_clients_slaves' => 0,
  'mem_clients_normal' => 20504,
  'mem_aof_buffer' => 0,
  'mem_allocator' => 'jemalloc-5.1.0',
  'active_defrag_running' => 0,
  'lazyfree_pending_objects' => 0,
  'lazyfreed_objects' => 0,
)
MaxMemory Eviction Policy config: noeviction
MaxMemory config: 4294967296

Performing some tests:
Redis is connected: 1
Connection works in general
Success for method set(testKey, value)
Success for method setnx(testnxkey, value)
Success for method setex(testexkey, 5, value)
Success for method set(testKeyWithNx, value, array (0 => 'nx',))
Success for method set(testKeyWithEx, value, array ('ex' => 5,))
Initial expire seems to be set correctly
setIfNotExists works fine
expireIfKeyHasValue seems to work fine
Extending expire seems to be set correctly
expireIfKeyHasValue correctly expires only when the value is correct
Expire is still set which is correct
deleteIfKeyHasValue seems to work fine
List feature seems to work fine

Done

**Comment by AltamashShaikh** [comment]
@skitoxe Does running `./console queuedtracking:print-queued-requests --queue-id=0 -vvv` prints anything ?

**Comment by skitoxe** [comment]
@AltamashShaikh The output from that command gives 6632 lines of requests. I need some more info as to what specifically to look for. I see nothing obvious jumping out at me at the beginning or end of file.

**Comment by atom-box** [comment]
@skitoxe 
I will leave Altamash to reply properly but as a note on number of lines, you can experiment with decreasing the _verbosity_.
 
In **Symfony PHP** control the number of output lines usually by:
-v brief output, just warnings and errors
-vv longer output
-vvv super detailed, with de-bugging statements all over the place

**Comment by AltamashShaikh** [comment]
@skitoxe If you run `./console queuedtracking:process --queue-id=0 --force-num-requests-process-at-once=1 -vvv` will this process any request or any error message in the console ?

**Comment by skitoxe** [comment]
@AltamashShaikh No, it wont process anything, tried with 1 and 20;
```
Forcing queue ID: 0
Force proccess num requests at once: 1
Starting to process request sets, this can take a while

This worker finished queue processing with 0req/s (0 requests in 0.04 seconds)

[hanric01adm@ictdmz330 ~]$ sudo -su nginx /usr/bin/php80 /var/www/matomo/console queuedtracking:process --queue-id=0 --force-num-requests-process-at-once=20 -vvv
Forcing queue ID: 0
Force proccess num requests at once: 20
Starting to process request sets, this can take a while

This worker finished queue processing with 0req/s (0 requests in 0.01 seconds)
```

@atom-box Yes, ive checked some different levels of verbosity before i opened issue as well.
But as it stands now:
-v = 9900 rows
-vv = 13000 rows
-vvv = 16800

So unless i know what to look for its to unwieldy to analyze. I've tried to search the text for common messages, such as "error" or "warrning" etc. But that returns nothing.

**Comment by AltamashShaikh** [comment]
@skitoxe Without any error its very tough to determine what is the cause of this, may be the queue is locked or there is something else.
We can check the lock status using `./console queuedtracking:lock-status` and check if that's the cause

**Comment by skitoxe** [comment]
As for the lock-status, i tried fiddling with that as well before creating the support ticket. It doesnt really do anything it appears, see below:

[<redacted_user>@<redacted> ~]$ sudo -su nginx /usr/bin/php80 /var/www/matomo/console queuedtracking:lock-status
"QueuedTrackingLock0" is locked for 18059 ms
Set option --unlock=QueuedTrackingLock0 to unlock the queue.

[<redacted_user>@<redacted> ~]$ sudo -su nginx /usr/bin/php80 /var/www/matomo/console queuedtracking:lock-status --unlock=QueuedTrackingLock0

Key QueuedTrackingLock0 unlocked

[<redacted_user>@<redacted> ~]$ sudo -su nginx /usr/bin/php80 /var/www/matomo/console queuedtracking:lock-status
"QueuedTrackingLock0" is locked for 25595 ms
Set option --unlock=QueuedTrackingLock0 to unlock the queue.

**Comment by skitoxe** [comment]
@AltamashShaikh i've recived an exception when trying to force process with debugging turned on now. i've sent that log to matmo support now.

**Comment by snake14** [comment]
Hi @skitoxe. I'm sorry that you're experiencing this issue. If you haven't already, you could try making the [change suggested in a different issue](https://github.com/matomo-org/plugin-QueuedTracking/issues/194#issuecomment-1488172290). That should allow the plugin to skip any errors that get thrown by bad requests and process the good requests. We're hoping to make a similar change in our next release of this plugin.

**Comment by skitoxe** [comment]
@snake14 @AltamashShaikh @atom-box 

I have now managed to resolve this situation and the queue is fine again!
What i did as a final resolution was to use the LPOP command in redis-cli to remove the first entry in trackingQueueV1 that matomo support told me was the default queue, after that I managed to push all requests through over time.

So we managed to avoid any major data loss.
The messaged I “pop:ed” i sent to matomo support to hope you can analyze it and see why it got stuck.
It’s not human readable. So im hoping that you guys can make sense of it and tell me why this message got stuck, And what I need to change to avoid this from recurring.

Thanks for the help thus far everyone.

@snake14 :
That seems like a good change to make, the way it works now is kind of dangerous in the sense that if you we're to run lets say 16 workers and one gut stuck, you might not notice that 5% of data is missing over time and will run redis oom if left alone, that is if you don't manually check the queues or write a script that monitors the queue. After this it feels like i'll have to sit down and write something that monitors the queue and alerts if it gets larger than confgured.
