### ISSUE TITLE
JSON error make the queue grow and Redis needs restart

### ISSUE THREAD

**Issue by mikkeschiren** [piwik/plugin-QueuedTracking#217]
I am not sure this has to do with this plugin per see, but with Queuetracking enabled and when we run `queuedtracking:process` in some rare cases we have gotten an error like this:

```
Uncaught exception in /var/www/html/core/Common.php line 529:
json_decode(): Argument #1 ($json) must be of type string, array given
2023-05-29 20:28:06,125 INFO success: queuedtracking-process_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-29 20:28:06,184 INFO exited: queuedtracking-process_00 (exit status 0; expected)
```
It seems that the only solution to the issue is to restart redis, and lose the tracking requests in the queue.

**Comment by mikkeschiren** [comment]
Plugin version: 4.0.6
Matomo version: 4.14.2
PHP version: 8.0.28
PHP Redis version: 5.3.7
Redis server version: 6.2.12

**Comment by AltamashShaikh** [comment]
@mikkeschiren does upgrading the plugin to latest version fixes your issue ??

**Comment by mikkeschiren** [comment]
Unsure :) - We had similar issues throughout versions, but we will upgrade and see if that solves the issue.

**Comment by AltamashShaikh** [comment]
@mikkeschiren version 4.0.7 has a fix for similar issues, so I would recommend updating the plugin first and try

**Comment by mikkeschiren** [comment]
Ok, we will try that.

**Comment by AltamashShaikh** [comment]
@mikkeschiren Did it fix the issue for you ?

**Comment by AltamashShaikh** [comment]
@mikkeschiren Closing this issue, if you need more help feel free to comment down and we can reopen the issue
