### ISSUE TITLE
Queue id should try to be more random

### ISSUE THREAD

**Issue by alexgarel** [piwik/plugin-QueuedTracking#231]
From what I understand, [queueid is based on userId taking the first letter](https://github.com/matomo-org/plugin-QueuedTracking/blob/5.x-dev/Queue/Manager.php#L214).

This seems very fragile to me to insure a good repartition of the requests !
I think in our case, we put a lot of requests to the same userid, and this make the queue 0 grow and grow a lot, without being able to catch-up, while other queues are doing well.

Although it's not documented, I assume there is a good reason to base on userId ? Maybe to ensure that events are inserted in correct order ?

**Comment by alexgarel** [comment]
Could we for example use a hash of userId + IP address, then use last letter.

**Comment by snake14** [comment]
Hi @alexgarel . Thank you for taking the time to create this issue. That method appears to be using the visitorId, not the userId. As idVisitor is a generated 16 digit hex unique ID that's then converted to a binary value, it should be pretty randomised. Yes, you do have some visitors that perform many actions, but over time that should be relatively evenly split between queues.

Is that explanation sufficient or would you like to submit this as an improvement request?

**Comment by alexgarel** [comment]
Hi @snake14, thanks for the quick answer.

I understand that it works for the case of the visitor id being random enough.

Maybe it's on our side that we do the mistake of a flat visitor id (tracking events with the mobile app).

I will maybe propose a PR for documentation (although it's not clear to me how this visitor id is computed, as my requests does not send a cid).
