### ISSUE TITLE
Queued tracking enabled, but no requests appear in queue

### ISSUE THREAD

**Issue by lpowalka** [piwik/plugin-QueuedTracking#244]
## Summary
The `QueuedTracking` plugin is configured correctly and enabled, but no requests appear in the queue and they keep being written directly to the database (that works fine). Restarting the servers after the Plugin was installed and configured did not help either.

When I run:
```
php /opt/bitnami/matomo/console queuedtracking:test
```
The output suggest that everything works correctly. Full output further below.

When I run:
```
php /opt/bitnami/matomo/console queuedtracking:monitor
```
The output shows that no new requests appear in the queue (checked in both of the Matomo servers/pods):
```
Queue is enabled
Request sets in the queue will be processed automatically after a tracking request
Up to 1 workers will be used
Processor will start once there are at least 50 request sets in the queue
0 (0) request sets left in queue. 7.24M used memory (13.01M peak). 0 workers active.
```

Inspecting the content of the Redis database (as configured in the plugin), the only present key is `fooList`, created by the `queuedtracking:test` command.

## Setup
Load-balanced Matomo by Bitnami (5.0.3) in Kubernetes:
- 2 matomo servers (shared NFS volume)
- Mariadb 11.3.2
- Redis used for caching
- QueuedTracking 5.0.4 (enabled)

Output of the `queuedtracking:test` command:
```
Settings that will be used:
Backend: redis
NumQueueWorkers: 1
NumRequestsToProcess: 50
ProcessDuringTrackingRequest: 1
QueueEnabled: 1

Redis backend only settings (does not apply when using MySQL backend):
Host: _host_
Port: _port_
Timeout: 0
Password: _pass_
Database: _database_ (Other than for Matomo RedisCache)
UseSentinelBackend: 0
SentinelMasterName: mymaster

Version / stats:
PHP version: 8.2.20
Uname: Linux matomo-7475d7699-zc8f4 5.15.146+ #1 SMP Fri Mar 8 13:04:16 UTC 2024 x86_64
PHPRedis version: 6.0.2
Backend version: 7.2.4

Redis is connected: 1
Connection works in general
Success for method set(testKey, value)
Success for method setnx(testnxkey, value)
Success for method setex(testexkey, 5, value)
Success for method set(testKeyWithNx, value, array (0 => 'nx',))
Success for method set(testKeyWithEx, value, array ('ex' => 5,))
Initial expire seems to be set correctly
setIfNotExists works fine
expireIfKeyHasValue seems to work fine
Extending expire seems to be set correctly
expireIfKeyHasValue correctly expires only when the value is correct
Expire is still set which is correct
deleteIfKeyHasValue seems to work fine
List feature seems to work fine
```

**Comment by snake14** [comment]
Hi @lpowalka . Thank you for taking the time to create this issue. I'm sorry to hear that you're experiencing trouble. I'm not seeing any issue in the settings that you shared and I can't reproduce the issue you've described. You mentioned rebooting the servers; have you tried disabling the plugin and then enabling it again?

Any ideas @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@lpowalka You have `ProcessDuringTrackingRequest=1` can you disable that and try ??
![Screenshot from 2024-06-20 07-00-57](https://github.com/matomo-org/plugin-QueuedTracking/assets/14902277/fd0b4a5d-ad93-4837-a57e-a08b16e86437)

**Comment by lpowalka** [comment]
Thank you for your quick replies. After coming back the next day I noticed that the setup now works, without changing or restarting anything. New keys `QueuedTrackingLock0` and `trackingQueueV1`  appear in Redis. 

It seems like it needed some time to activate - at least the 3 hours when I was trying to debug it. Could it be caused by the fact that I activated it during active traffic (around 15k actions per hour)?

**Comment by snake14** [comment]
Hi @lpowalka . I'm glad that the issue has resolved itself. Yes, if you have the setting to process during tracking request enabled and there's high traffic, it's possible that the queue would get cleared so fast that you wouldn't see any requests in the queue. Although, that's still low enough traffic that it would take a few seconds to fill the queue with 50 requests. So, I would expect to see at least some requests in the queue. It might have just been a quirk of your server configuration. Once again, I'm glad that things appear to be working as expected now :+1:
