### ISSUE TITLE
Redis Sentinel not working

### ISSUE THREAD

**Issue by RentYourAdmin** [piwik/plugin-QueuedTracking#254]
I couldnt get QueuedTracking with Sentinel to work.
It is working since i changed:

`$this->timeout === 0.05;`

to

`$this->timeout = 0.05;`

in line 42 in /plugins/QueuedTracking/Queue/Backend/Sentinel.php

Maybee this should be fixed.

**Comment by randy-innocraft** [comment]
Hi @RentYourAdmin. Thank you for creating the issue and bringing this to our attention, that's very appreciated. We have reviewed and triaged the problem internally, and we have confirmed it is an issue. Our team will prioritise this, and we will update you on the progress here when we have an update to share. If you have any further information or questions, please feel free to add them here.

**Comment by snake14** [comment]
@RentYourAdmin Thank you for pointing out this issue. I have applied the fix that you suggested, and it should be included in the next scheduled release of this plugin.
