### ISSUE TITLE
"QueuedTrackingLock0" is locked for 19147 ms

### ISSUE THREAD

**Issue by centminmod** [piwik/plugin-QueuedTracking#29]
when running `console queuedtracking:lock-status` i get

```
"QueuedTrackingLock0" is locked for 19147 ms
Set option --unlock=QueuedTrackingLock0 to unlock the queue.
 
"QueuedTrackingLock1" is locked for 17983 ms
Set option --unlock=QueuedTrackingLock1 to unlock the queue.
```

```
Queue is enabled
Request sets in the queue will be processed automatically after a tracking request
Up to 2 workers will be used
Processor will start once there are at least 10 request sets in the queue
908 (555+353) request sets left in queue. 4.57M used memory (4.57M peak). 1 workers active.   
```
how do i pass the unlock option ?

Was running fine on PHP 5.6.16 with phpredis 2.27 but now just updated to PHP 5.6.17 with phpredis 2.2.7

**Comment by tsteur** [comment]
it's `console queuedtracking:lock-status --unlock=QueuedTrackingLock1`

It's locked for a long time which looks like you are using it with Log Importer? Queuedtracking plugin is not really built to use it in combination with Log importer but if you do, we recommend to set the "Number of requests to process" to 1 as the log importer usually sends multiple requests at once using bulk tracking already.

**Comment by centminmod** [comment]
thanks @tsteur 

FYI, i'm not using any log importing AFAIK

**Comment by l36t** [comment]
I encounter this problem too.@tsteur.I execute queuedtracking:lock-status --unlock=QueuedTrackingLock0,but still tell me :
"QueuedTrackingLock0" is locked for 17983 ms
Set option --unlock=QueuedTrackingLock1 to unlock the queue.
I'm not using any log importing.
Another problem is,redis sometimes hang on and logs :
# Accepting client connection:accept:unknow error

**Comment by tsteur** [comment]
Seems like this could be a redis issue see eg https://github.com/MSOpenTech/redis/issues/435 . I haven't really found much about this error otherwise apart from eg something like https://qnalist.com/questions/6157585/redis-db-redis-sentinel-start-a-loop-when-the-master-instance-is-down . Are you using Redis Sentinel feature? Which OS? If not yet done I'd try to update to the latest Redis version and check logs. You may be also interested in "deubgging" redis etc. I cannot really help much with this error unfortunately

**Comment by l36t** [comment]
thanks for your reply,I decide to use linux,not windows.lock problem not solved.
Key QueuedTrackingLock0 unlocked
"QueuedTrackingLock0" is locked for -2 ms
Set option --unlock=QueuedTrackingLock0 to unlock the queue

I execute C:\phpEnv\php\php.exe "C:\phpEnv\Apache24\htdocs\piwik\console"  queuedtracking:lock-status  --unlock=QueuedTrackingLock0  ,but still tell me unlocked as above.@tsteur

**Comment by tsteur** [comment]
I think in this case it actually says "-2" which means the key is not locked so it should be all good. I have created an issue for this: https://github.com/piwik/plugin-QueuedTracking/issues/42 and hope to provide a fix for it soon

**Comment by mattab** [comment]
The issue should be fixed in latest version of QueuedTracking plugin, please check @l36t @centminmod
