### ISSUE TITLE
Worker is unable to read requests from queue

### ISSUE THREAD

**Issue by andrzejewsky** [piwik/plugin-QueuedTracking#32]
Recently, We have needed to do something in the database, so we had to stop all of the queue workers.
Meanwhile, the queue was still saving all of the requests. When we finished, in order to replay all saved data, we turned on all workers again (we had greater than 20GB data in the Redis!).

Everything was ok, until situation when 8 of workers was empty, and the rest 8 was unable to read the requests. In this point, we decided to turn off all workers again and run only one of them. Then we saw strange error:

```
[Piwik\Plugins\QueuedTracking\Queue\LockExpiredException]                                            
  Rolled back during finishing as we no longer have the lock or the lock was never acquired. So far track  
  er processed 0 requests 
```

After a lot of time debugging with a sys-admins team, we found out where was the problem.

Let's consider these lines: https://github.com/piwik/plugin-QueuedTracking/blob/master/Queue/Processor.php#L173-L174

We came to the situation when $ttl was 20, but the time of processing requests was greater than 20 seconds and after increasing this limit from 20 to 30 seconds, mentioned exception was disappeared.

What do you think, it's some edge case? or maybe you should implement some "retry" mechanism?
Because right now, in some error case (eg. exception etc.) queue will stop.

**Comment by tsteur** [comment]
If up to 10 requests take more than 20 seconds in total. Meaning each tracking request would take on average more than 2 seconds which shouldn't be the case. 

Have you checked the error logs if there are any error messages? Maybe also check some system logs. Maybe it is similar to https://github.com/piwik/plugin-QueuedTracking/issues/22#issuecomment-181416958 and https://github.com/piwik/plugin-QueuedTracking/issues/22#issuecomment-182244107

There is already a "retry" mechanism in case requests could not be inserted but when we do not have the lock anymore we kinda just have to stop as possibly another worker took over the processing. What we could do in such a case is starting to acquire the lock again but it would possibly continue processing on another queue (which shouldn't be bad).

**Comment by quba** [comment]
It's possible that there were only a few problematic requests in the queue that took much longer and they were locking the whole process.

**Comment by quba** [comment]
BTW. maybe it was a set of requests (bulk tracking) and that was the reason it took so long?

**Comment by tsteur** [comment]
If there are many requests from a bulk tracking request, the TTL gets bigger as it is `$numberOfRequests * 2`. So if there are 100 requests, it will be set to 200 seconds.

**Comment by quba** [comment]
It's weird. Most likely it was something with requests in the queue. If it's not the reverse DNS lookup, then I don't have further ideas. However, setting $ttl to 30 sec instead of 20 helped in this case. Maybe the solution here is to set it to 30 sec and add additional logging in case it's not enough? Or just to add some more logging to check these requests separately?

**Comment by tsteur** [comment]
I'm not sure what you refer to with logging, I might take 2 steps:

* I increase default $ttl to 30. 
* I will try to log a request if it takes more than 2 seconds. Can you see normal log output from tracking? Cause usually it would be only logged if tracker debug is enabled.

**Comment by tsteur** [comment]
I've created a PR here but I'm not sure if you'd actually see it in the logs: https://github.com/piwik/plugin-QueuedTracking/pull/36

**Comment by quba** [comment]
:+1: 
In case this issue reoccurs, we will enable tracker debug mode and check the output (e.g. log the output to a file).

**Comment by tsteur** [comment]
done
