### ISSUE TITLE
Can't connect QueuedTracking with Redis unix socket /var/run/redis.sock

### ISSUE THREAD

**Issue by kuonsam** [piwik/plugin-QueuedTracking#37]
Dear piwik, please help to update if there is the way that can make queuedtracking to connect with redis by using unix socket instead of using TCP, ip address 127.0.0.1

**Comment by michaelnordmeyer** [comment]
Wasn't this issue resolved with #47?

**Comment by tsteur** [comment]
Yep, should have been resolved. Please let me know if you still experience the issue.

**Comment by quenenni** [comment]
Hello,

Piwik v3.1.1
Queued trackung v3.0.1


I can't set the option "Redis-port" to 0 -> Err msg: "Redis port: Port has to be at least 1"
```
Port the Redis server is running on. Value should be between 1 and 65535. Use 0 if you are using unix socket to connect to Redis server.
Default: 6379 
```

Do I have to put the sock file path (despite the tip)?

**Comment by quenenni** [comment]
Ok..

Sorry, I thought I only had to set 0 to the field "Redis port" and I forgot to set the field "Redis host or unix socke" to "/var/run/redis/redis.sock".
My bad.

And.. great it's working fine.
