### ISSUE TITLE
Rolled back as we no longer have lock or the lock was never acquired

### ISSUE THREAD

**Issue by Klef** [piwik/plugin-QueuedTracking#4]
Good day.
i use this plugin, i disable "Process during tracking request" and run ./console queuedtracking:process.
but i received a message [Piwik\Plugins\QueuedTracking\Queue\LockExpiredException]
  Rolled back as we no longer have lock or the lock was never acquired

if enable "Process during tracking request" query  is increasing
$ ./console queuedtracking:monitor
Queue is enabled
The command ./console queuedtracking:process has to be executed to process request sets within queue
Processor will start once there are at least 100 request sets in the queue
38195 request sets left in queue. 371.49M used memory (371.49M peak)

**Comment by tsteur** [comment]
Which Redis version are you using? Are you using the JavaScript tracker?
Is there more information about this error? Eg in which line it occurs?

**Comment by Klef** [comment]
Redis server v=2.8.19
all settings standart
not use JavaScript tracker
Details will try to identify the other day

**Comment by tsteur** [comment]
Thx for your feedback so far. If you do not use the JavaScript tracker, what do you use then? Do you call the `piwik.php` Tracker API directly?

**Comment by ofedoryshyn** [comment]
I have the same issue :(
we use piwik.php to track ios/android application

**Comment by tsteur** [comment]
Can you access the redis-cli and execute `SET resource-name anystring NX EX 60` what is the response? 

Can you also within 60 seconds execute `eval "if redis.call(\"GET\",KEYS[1]) == ARGV[1] then\n return redis.call(\"EXPIRE\",KEYS[1], ARGV[2])\n else\n return 0 end" 1 "resource-name" "anystring" 2`

What is the response? And what is the response a minute later?

eg in my case it is
```
127.0.0.1:6379> SET resource-name anystring NX EX 60
OK

127.0.0.1:6379> eval "if redis.call(\"GET\",KEYS[1]) == ARGV[1] then\n return redis.call(\"EXPIRE\",KEYS[1], ARGV[2])\n else\n return 0 end" 1 "resource-name" "anystring" 2
(integer) 1

// a minute later
127.0.0.1:6379> eval "if redis.call(\"GET\",KEYS[1]) == ARGV[1] then\n return redis.call(\"EXPIRE\",KEYS[1], ARGV[2])\n else\n return 0 end" 1 "resource-name" "anystring" 2
(integer) 0
```

**Comment by ofedoryshyn** [comment]
the same

**Comment by tsteur** [comment]
@ofedoryshyn do you mean you get the same response?

**Comment by tsteur** [comment]
Also do you maybe see something in the Redis log file? Is it maybe possible to get access to a server to debug?

**Comment by tsteur** [comment]
Are you all using the command line to process requests in the queue (`./console queuedtracking:process`)? Is it possible that you terminated it eg via `ctrl+c`?

**Comment by ofedoryshyn** [comment]
error log is clean
Yes. It's possible that I terminate process via ctrl+c

**Comment by tsteur** [comment]
Thx I noticed that problem myself. I don't think there is much we can do to prevent it. I added a new command `./console queuedtracking:lock-status` that can remove the lock if needed. This will be available in a new version that will be released soon. I will also add a FAQ for this case.

Usually either tracking requests are processed during a normal tracking request (in this case it cannot happen that someone cancels it and if a request is terminated we get notified and can unlock the queue automatically) or via the console command (they are usually supposed to run as a cronjob etc and are usually not terminated via `ctrl+c`)

**Comment by tsteur** [comment]
Thx! Actually, I think `ctrl+c` is not related to this sorry. When terminating a command this way it will only take a while until a new processor can start.

**Comment by tsteur** [comment]
Does it still occur with the latest version?

**Comment by tsteur** [comment]
Will close this issue, please reopen in case you can still reproduce

**Comment by hkm15022001** [comment]
Hi @tsteur. I am facing this issue in latest version, when I set Number of request that are processed in one batch is 1000. Redis works perfectly fine

**Comment by AltamashShaikh** [comment]
@hkm15022001 Can you please elaborate more on the issue you are facing ?

**Comment by hkm15022001** [comment]
I am having problems handling large loads (1500 rps) when doing load testing. I am setting up queue tracking with redis sentinel, _number of queue_ is 8, **number of requests that are processed in one batch** is 100. I manually create workers using cronjob with the command queuedtracking:process --queue-id=.... With the above configuration, each of my workers only has a processing speed of about 25 req/s. I tried increasing the **number of requests that are processed in one batch** to 1000, then the worker got the error **_Rolled back as we no longer have lock or the lock was never acquired_**. Now I am very confused, not knowing whether the bottleneck is in Redis or DB or my workers jobs

**Comment by AltamashShaikh** [comment]
@hkm15022001 We made significant improvement in #252 and it does handle the load specified, this error could occur if another process would be processing same request set, may be something is running, try running `./console queuedtracking:monitor` to monitor the requests.

**Comment by AltamashShaikh** [comment]
@hkm15022001 You can also use `console queuedtracking:lock-status` command to check the status of your lock.

**Comment by hkm15022001** [comment]
This is my output
/console queuedtracking:lock-status
"QueuedTrackingLock0" is locked for 43137 ms
"QueuedTrackingLock3" is locked for 41187 ms
.... 
Set option --unlock=QueuedTrackingLock0 to unlock the 
And i have a question, when using multiple workers, SQL DB only allows 1 worker to write at a time and does not allow parallel processing. So does setting up multiple workers really improve performance?
Lock

**Comment by AltamashShaikh** [comment]
@hkm15022001 If you are using 'InnoDB` engine, it will be concurrent.

MySQL uses row-level locking for InnoDB tables to support simultaneous write access by multiple sessions, making them suitable for multi-user, highly concurrent, and OLTP applications.

You just need to set the correct no of workers and no of requests to process in a batch depending on your server size.

**Comment by hkm15022001** [comment]
@AltamashShaikh I deployed matomo on Kubernetes with Bitnami Helm Chart, with cronjobs creating dedicated pods for processing requests from queues. When the load was high, I saw a lot of requests set in the queue using the queuedtracking:monitor command, but the workers processed requests very slowly (1 worker~25req/s). According to the monitor, these workers used very little cpu and ram(i want it to be used more) . When increasing no requests are processed in one batch to 1000, the error
 **Rolled back as we no longer have lock or the lock was never acquired. So far tracker processed 1000 requests**. 
Looking forward to receiving your suggestions

**Comment by AltamashShaikh** [comment]
@hkm15022001 May be try increasing the workers to 16-32 and request to 50 and see the load on your server

**Comment by hkm15022001** [comment]
thanks @AltamashShaikh for suggestion
I configured 16 workers and no request in one batch is 50. As a result, each worker can only process 4 req/s and workers do not consume resources, too bad. Is it related to database?

**Comment by AltamashShaikh** [comment]
@hkm15022001 Is this really 1500QPS ? Can you check correct data is being logged ?

**Comment by hkm15022001** [comment]
@AltamashShaikh Yes, I definitely run stress test successfully, I saw a lot of requests in the queue when running the queuedtracking:monitor command

**Comment by AltamashShaikh** [comment]
@hkm15022001 Can you check you visitsLog or visitsSummary page if the data looks good to you there ?

**Comment by hkm15022001** [comment]
@AltamashShaikh Okay, I see both actions and visitors on the report interface with the same number as the total number of tracking requests. The only thing is that the worker is too slow and in a production environment it will not meet the requirements.

**Comment by AltamashShaikh** [comment]
@hkm15022001 Try doing this 16 workers and no of requests as 5 and see the performance

**Comment by hkm15022001** [comment]
@AltamashShaikh performance remains unchanged 🥲

**Comment by hkm15022001** [comment]
@AltamashShaikh
Today I saw with 16 workers and 5 no request process the performance increased, but it is sometimes good and sometimes not. Do you have any more suggestions for me?Thank you very much

**Comment by snake14** [comment]
Hi @hkm15022001 . I'm sorry to hear that you're experiencing this issue. In the future, please create a new issue and link to any related previous issues instead of commenting on a closed (old) issue.

In general, we typically see better performance with a higher number of workers and lower requests per batch. It sounds like that isn't your experience, though. It seems like the database might be causing a bottleneck. Have you tried running any monitoring on the database side?
