### ISSUE TITLE
Potential optimizations

### ISSUE THREAD

**Issue by adaqus** [piwik/plugin-QueuedTracking#40]
Hi @tsteur . PiwikPRO is going to use this plugin more extensively with very high traffic. We would like increase maximum number of workers and make some code optimizations (if there are some worth to implement). So I have some questions:

1. Does increasing number of workers come down to just changing value in following line: https://github.com/piwik/plugin-QueuedTracking/blob/master/Settings.php#L236? Why there is upper limit for number of workers??
2. As an author of this plugin, could you tell where do you see potential optimizations/improvements in the plugin's codebase?

**Comment by tsteur** [comment]
1) yes I'd say so. Upper limit don't remember exactly. Think at some point MySQL "locks" each other too badly etc. Also there is more and more overhead when there are more workers re one which queue to work on but that shouldn't be too bad. I think we did some tests that time and performance got worse with 16 workers but obviously depends on number of CPUs and database etc.

2) I'd recommend to have a look at other issues in this repo. For sure there are more tweaks to do to make it faster but takes a lot of time. In general profiling, caching, checking how to process the entries that are queued in a smarter way without having to do duplicate work etc.

**Comment by tsteur** [comment]
Keep in mind this plugin was not developed for performance initially, only to handle peaks of traffic better

**Comment by adaqus** [comment]
@tsteur thank you for fast and detailed answer :) We will do some test on heavy load.
