### ISSUE TITLE
Piwik 3.0.0.rc3 support

### ISSUE THREAD

**Issue by andypl78** [piwik/plugin-QueuedTracking#49]
Please add support for Piwik 3.0.0rc3

**Comment by tsteur** [comment]
Is something not working for you?

**Comment by andypl78** [comment]
During the upgrade to 3.0.0.rc3 I had a message that the plugin is incompatible and will be turned off.
But, however, I installed it and running so you can close the topic.

**Comment by tsteur** [comment]
Thank you for letting us know 👍
