### ISSUE TITLE
can't connect to redis server

### ISSUE THREAD

**Issue by ntimo** [piwik/plugin-QueuedTracking#50]
Hi their,
I have a local redis server running in docker using the standart redis image. And when I try to set it up with the plugin. It always gives me an connection error. 

I am running php 7.1 with the redis extension installed.
I used the 127.0.0.1 ip and the port I entered into docker. I am using 6374 as port.

Thats the image I use: https://hub.docker.com/_/redis/

Thank you for your help
Timo

**Comment by tsteur** [comment]
Do you get any error message? Or can you see in redis whether Piwik is actually trying to connect to redis?

**Comment by ntimo** [comment]
Hi, 
I get this message from piwik: Queue enabled: Connection to Redis failed. Please verify Redis host and port

And the server log and the redis console show nothing...

**Comment by zloyudav** [comment]
Hello.
Just use pconnect instead of connect, and everything will be fine. 
/Queue/Backend/Redis.php string 236.
