### ISSUE TITLE
Allow for Redis Settings to be changed with Plugin

### ISSUE THREAD

**Issue by davidfisk** [piwik/plugin-QueuedTracking#53]
Hi,

I would like to override the way QueuedTracking retrieves its Redis settings, but am having problems determining how to do this without modifying the QueuedTracking code directly. 

For our Piwik DB connection, we were able to create a custom plugin and register custom db connection events and override the settings. It would be perfect if the QueuedTracking plugin also posted a similar event with the settings once it retrieved its settings so that the settings could be altered via plugin 

For reference, see Piwik::postEvent() usage in Piwik /core/Db.php getDatabaseConfig() function.

Thanks

**Comment by tsteur** [comment]
You can use `Piwik\Config::getInstance->QueuedTracking = array()` config to configure it. Or do it in the config file directly. Eg `array('numQueueWorkers' => '...', 'numRequestsToProcess' => '', 'queueEnabled' => '', 'redisHost' => '')`... You can find the config settings by going to "Administration => Config file" as super user

**Comment by davidfisk** [comment]
Hi,

This is not adequate for my needs. In my environment, I need to change the method in which the password is retrieved programatically. More than just reconfiguring the values.

For security reasons, I need to read the password from disk using some specific decryption functions. Currently there is no way to override this behavior that I can see.

For our database connection, we were able to update how the password was retrieved by using the reference to the settings provided in the callback in the previously mentioned DB code: (Piwik::postEvent() usage in Piwik /core/Db.php getDatabaseConfig() function).

It would be very helpful if Process.php posted a similar event (with a reference to the settings as the callback) after retrieving the settings so that any values in the settings can be modified programmatically. 

https://developer.piwik.org/guides/events

Thanks,
David

**Comment by tsteur** [comment]
I think you could create a `config/config.php` in your plugin and do something like this:

```php
<?php
return array(
    'Piwik\Config' => DI\decorate(function ($previous) {
        $tracking = $previous->QueuedTracking;
        $tracking['redisPassword'] = trim(file_get_contents('....'));
        $previous->QueuedTracking = $tracking;

        return $previous;
    }),
);
```

An event would be possible as well to post but likely not needed

**Comment by davidfisk** [comment]
I will try this, thanks for you help!

**Comment by davidfisk** [comment]
This works great. Thanks again for your help.

**Comment by tsteur** [comment]
Awesome 👍
