### ISSUE TITLE
Use non-blocking operations

### ISSUE THREAD

**Issue by zloyudav** [piwik/plugin-QueuedTracking#54]
Hi.
In your plugin you use the sequence of commands lrange + ltrim to get the specified number of list items. Since this operation is not atomic, you have to use a mutex and dimmed around it more dark just because the mutex is not reliable and can be removed in time. Instead, simply use

> 
> for ($i=0;$i<$numvalues;$i++){
> $values[]=$this->redis->lpop($key);
> }

It may seem that it's slower, but no - you will not be able to load the redis-instance from php enough so you can feel the difference. But you no longer need mutex or additional treatment to remove these data.

**Comment by tsteur** [comment]
This is implemented like this on purpose. The reason is to leave the requests in the queue until they were successfully processed. If there is any problem during processing X requests from the queue, they won't be removed and kept in there. Eg if DB is temporarily down. Does this explain it?
