### ISSUE TITLE
Real time figure not working when Queue enabled

### ISSUE THREAD

**Issue by AlifAzmi** [piwik/plugin-QueuedTracking#60]
As per title

Please advice

![screen shot 2017-11-09 at 10 03 19 am](https://user-images.githubusercontent.com/15099864/32584846-6f5ff642-c535-11e7-8b7f-0261c152b579.png)

![screen shot 2017-11-09 at 10 06 24 am](https://user-images.githubusercontent.com/15099864/32584859-83dcf57a-c535-11e7-91e7-fb4fd61919af.png)

**Comment by tsteur** [comment]
Are other reports working? It looks like the processing of requests is not actually working.

**Comment by AlifAzmi** [comment]
Thanks for prompt reply. All other reports not working but it's fine when disable it.

After doing some checking, seems like all request successful store in redis but not sending response tu browser.

**Comment by tsteur** [comment]
Maybe execute `./console queuedtracking:test` in your Piwik installation to see if everything works. By the sounds the queued tracking is not working.

**Comment by AlifAzmi** [comment]
Thank you.

Here the screenshot from `./console queued tracking:test`

![screen shot 2017-11-09 at 11 35 45 am](https://user-images.githubusercontent.com/15099864/32587214-14e1c81e-c542-11e7-8c55-47c98a7b7939.png)

**Comment by tsteur** [comment]
What is the output of `./console queuedtracking:monitor`
 and is `./console queuedtracking:lock-status` printing something?

**Comment by AlifAzmi** [comment]
Thank you again @tsteur 

`./console queued tracking:monitor`
![screen shot 2017-11-09 at 12 41 17 pm](https://user-images.githubusercontent.com/15099864/32588651-40faccf8-c54b-11e7-8524-5ab8b880c396.png)

`./console queuedtracking:lock-status`
not showing anything

**Comment by tsteur** [comment]
I presume everything looks good so far. Maybe you can issue some more tracking requests and see if the requests are actually processed? (basically the number of requests should not get much higher than 5). Also when using "process during tracking request" is enabled, I would recommend to set the number of workers to `1` instead of `2`.

Might be also worth trying to execute `./console queuedtracking:process` once

**Comment by AlifAzmi** [comment]
Thank you @tsteur 

Seems like it's working when I try to decrease number of request per batch to `1`. So I assume, It waited for batch to meet the asking request then send to the browser.

**Comment by tsteur** [comment]
Awesome 👍  will close the issue then
